# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Names"                                # Your name
  description: "This is a short description"   # A brief slogan (optional) -> is displayed on search engines (as short description)
  image: img/my_image.jpg
  
  favicon: img/favicon.png # icon on top left of website (in tab)
  
  # start of the navigation bar at the top of the website
  navbar: # on top of website
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd # file for this projects is in directory projects in file index.qmd (some other quarto file)
      - text: "Photography"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
      - text: "Fancy Stuff"
        href: fancy/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      - icon: twitter
        href: https://twitter.com/MarvinSchmittML
      - icon: linkedin
        href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: envelope
        aria-label: email
        href: "mailto:mail.marvinschmitt@gmail.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true